### ISSUE TITLE
Error when copying emoticon to clipboard

### ISSUE THREAD

**Issue by madsroskar** [xxczaki/oji#1]
Once I finish creating an emoticon, and select to copy it to the clipboard (I did this by going with the default Y), I get the following error:

```
Something bad happened (︶︹︺)
Error
    at Function.module.exports.sync (/usr/local/lib/node_modules/oji/node_modules/execa/index.js:303:26)
    at Object.copySync (/usr/local/lib/node_modules/oji/node_modules/clipboardy/lib/macos.js:9:26)
    at Object.exports.writeSync.input [as writeSync] (/usr/local/lib/node_modules/oji/node_modules/clipboardy/index.js:38:13)
    at Object.when (/usr/local/lib/node_modules/oji/lib/functions.js:86:18)
    at /usr/local/lib/node_modules/oji/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/oji/node_modules/run-async/index.js:24:19
    at DeferSubscriber.Rx.Observable.defer [as factory] (/usr/local/lib/node_modules/oji/node_modules/inquirer/lib/ui/prompt.js:109:32)
    at DeferSubscriber._callFactory (/usr/local/lib/node_modules/oji/node_modules/rxjs/observable/DeferObservable.js:92:27)
    at DeferSubscriber.tryDefer (/usr/local/lib/node_modules/oji/node_modules/rxjs/observable/DeferObservable.js:85:18)
    at new DeferSubscriber (/usr/local/lib/node_modules/oji/node_modules/rxjs/observable/DeferObservable.js:81:14)
```

The complete output is:

```
? Welcome to OJI! Choose option: Create new emoji
? Choose left arm: ╰
? Choose right arm: ᕤ
? Choose left body: (
? Choose right body: )
? Choose left cheek: ”
? Choose right cheek: ”
? Choose left eye: o
? Choose right eye: o
? Choose nose/mouth: ω
This is your emoji: ╰(”oωo”)ᕤ
? Copy it to clipboard? Yes
Something bad happened (︶︹︺)
Error
    at Function.module.exports.sync (/usr/local/lib/node_modules/oji/node_modules/execa/index.js:303:26)
    at Object.copySync (/usr/local/lib/node_modules/oji/node_modules/clipboardy/lib/macos.js:9:26)
    at Object.exports.writeSync.input [as writeSync] (/usr/local/lib/node_modules/oji/node_modules/clipboardy/index.js:38:13)
    at Object.when (/usr/local/lib/node_modules/oji/lib/functions.js:86:18)
    at /usr/local/lib/node_modules/oji/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/oji/node_modules/run-async/index.js:24:19
    at DeferSubscriber.Rx.Observable.defer [as factory] (/usr/local/lib/node_modules/oji/node_modules/inquirer/lib/ui/prompt.js:109:32)
    at DeferSubscriber._callFactory (/usr/local/lib/node_modules/oji/node_modules/rxjs/observable/DeferObservable.js:92:27)
    at DeferSubscriber.tryDefer (/usr/local/lib/node_modules/oji/node_modules/rxjs/observable/DeferObservable.js:85:18)
    at new DeferSubscriber (/usr/local/lib/node_modules/oji/node_modules/rxjs/observable/DeferObservable.js:81:14)
```

OS: macOS Sierra 10.12.6
Terminal: iTerm2

Note: I'm using tmux, and I'm unsure whether that could cause the issue or not.

**Comment by xxczaki** [comment]
I think this might be a bug with [clipboardy](https://github.com/sindresorhus/clipboardy) module.

**Comment by xxczaki** [comment]
@madsroskar Update oji to version 1.0.7, should work now :smile:

**Comment by madsroskar** [comment]
I've updated, and it does seem to work now. Thanks!
